name: TEST CI

on:
  workflow_dispatch:

jobs:
  test_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Add reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // get all the teams in the organization
            const repos = await github.rest.repos
            // list all methods available for the repos object
            console.log(Object.getOwnPropertyNames(repos))
